#!/usr/bin/env python3
"""Generate static analysis HTML snapshot.
Usage:
  python scripts/build_analysis.py            # full rebuild (data.js + all HTML)
  python scripts/build_analysis.py --data-only # regenerate data.js only, leave HTML untouched
Output: analysis/ folder (open analysis/index.html, no server needed).
"""
import argparse, json, pathlib
from datetime import datetime

PROJECT_ROOT = pathlib.Path(__file__).parent.parent
RAW_DIR      = PROJECT_ROOT / 'responses' / 'survey' / 'raw'
PROCESSED_DIR= PROJECT_ROOT / 'responses' / 'survey' / 'processed'
# Output goes to the sibling GrooshiSurveyData repo (private, holds full data incl. contacts)
OUT_DIR      = PROJECT_ROOT.parent / 'GrooshiSurveyData' / 'analysis'
OUT_DIR.mkdir(parents=True, exist_ok=True)

CHARTJS = 'https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js'
PAGES   = ['index.html','section1.html','section2.html','section3.html',
           'section4.html','section5.html','meta.html','analysis.html']
TITLES  = {
    'index.html':    'לוח בקרה',
    'section1.html': 'סעיף 1 — רקע ופרופיל',
    'section2.html': 'סעיף 2 — בטיחות, תקשורת, משפטי',
    'section3.html': 'סעיף 3 — חיכוך',
    'section4.html': 'סעיף 4 — צורך ותשלום',
    'section5.html': 'סעיף 5 — סיום',
    'meta.html':     'מקורות גיוס',
    'analysis.html': 'ניתוח',
}

# ── data ─────────────────────────────────────────────────────────────────────

def load_responses():
    out = []
    for rp in sorted(RAW_DIR.glob('*.json'), key=lambda p: int(p.stem.split('_')[0])):
        with open(rp, encoding='utf-8') as f:
            raw = json.load(f)
        pp = PROCESSED_DIR / rp.name
        raw['_analysis'] = None
        if pp.exists():
            with open(pp, encoding='utf-8') as f:
                raw['_analysis'] = json.load(f).get('analysis')
        out.append(raw)
    return out

def write_data_js(responses, ts):
    text = ('// Auto-generated by scripts/build_analysis.py\n'
            '// Snapshot: ' + ts + '\n'
            'const SURVEY_DATA = ' + json.dumps(responses, ensure_ascii=False, indent=2) + ';\n')
    (OUT_DIR / 'data.js').write_text(text, encoding='utf-8')

# ── shared HTML assets ────────────────────────────────────────────────────────

CSS = '''
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif;
       background: #f5f6fa; color: #1a1a2e; direction: rtl; }
.topbar { background: #1a1a2e; color: #fff; padding: 12px 24px;
          display: flex; justify-content: space-between; align-items: center; }
.topbar h1 { font-size: 1rem; font-weight: 600; }
.topbar .snap { font-size: 0.72rem; opacity: 0.4; }
.nav { display: flex; justify-content: space-between; align-items: center;
       padding: 10px 22px; background: #fff; border-bottom: 1px solid #e8e8e8;
       position: sticky; top: 0; z-index: 10; box-shadow: 0 1px 3px rgba(0,0,0,.05); }
.nav a { display: inline-block; padding: 6px 16px; border-radius: 6px;
         text-decoration: none; font-size: 0.85rem; color: #555; background: #f0f0f0; }
.nav a:hover { background: #ddd; }
.nav a.primary { background: #1a1a2e; color: #fff; }
.nav .pg { font-size: 0.78rem; color: #bbb; }
.wrap { max-width: 860px; margin: 0 auto; padding: 24px 16px 60px; }
h2.ptitle { font-size: 1.3rem; font-weight: 700; margin-bottom: 2px; }
p.psub { font-size: 0.8rem; color: #aaa; margin-bottom: 20px; }
.sg { display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr));
      gap: 12px; margin-bottom: 20px; }
.st { background: #f0f4ff; border-radius: 8px; padding: 14px 12px; text-align: center; }
.st .n { font-size: 2rem; font-weight: 700; color: #1a1a2e; line-height: 1.1; }
.st .l { font-size: 0.72rem; color: #666; margin-top: 4px; }
.card { background: #fff; border-radius: 10px; padding: 18px 20px 20px;
        margin-bottom: 16px; box-shadow: 0 1px 3px rgba(0,0,0,.06); }
.ctitle { font-size: 0.9rem; font-weight: 600; margin-bottom: 2px; }
.cbase  { font-size: 0.72rem; color: #c0c0c0; margin-bottom: 12px; }
.ch { position: relative; }
.sm  { height: 130px; }
.md  { height: 210px; }
.lg  { height: 290px; }
.xl  { height: 400px; }
.dot { height: 160px; }
footer { text-align: center; font-size: 0.7rem; color: #ccc; padding: 20px; }
'''

SHARED_JS = r'''
function addCard(title, n, total, html) {
    var base = (total != null) ? 'n='+n+' מתוך '+total : 'n='+n;
    var el = document.createElement('div');
    el.className = 'card';
    el.innerHTML = '<div class="ctitle">'+title+'</div>'
                 + '<div class="cbase">'+base+'</div>'+html;
    document.getElementById('wrap').appendChild(el);
}
function ch(id, sz) {
    return '<div class="ch '+(sz||'md')+'"><canvas id="'+id+'"></canvas></div>';
}
var PAL=['#4f7ef8','#f87c4f','#4fc8a4','#f8c84f','#a04ff8',
         '#f84f7c','#4fb8f8','#84c84f','#f8844f','#607080'];
function freqChart(id, values, labels, base) {
    var counts = labels.map(function(l){
        return values.filter(function(v){ return v===l; }).length;
    });
    new Chart(document.getElementById(id), {
        type: 'bar',
        data: { labels: labels,
                datasets: [{ data: counts,
                             backgroundColor: PAL.slice(0, labels.length),
                             borderRadius: 4 }] },
        options: {
            indexAxis: 'y', responsive: true, maintainAspectRatio: false,
            plugins: {
                legend: { display: false },
                tooltip: { callbacks: { label: function(c) {
                    return ' '+c.raw+'  ('+(base>0?Math.round(c.raw/base*100):0)+'%)';
                }}}
            },
            scales: {
                x: { beginAtZero: true, ticks: { stepSize:1, precision:0 },
                     grid: { color:'#f5f5f5' } },
                y: { ticks: { font:{ size:11 }, color:'#333' },
                     grid: { display:false } }
            }
        }
    });
}
function multiFreq(id, rawArr, opts, base) {
    var flat = [];
    rawArr.forEach(function(v){
        if (v) v.split(', ').forEach(function(x){ flat.push(x.trim()); });
    });
    freqChart(id, flat, opts, base);
}
function histChart(id, nums, lo, hi) {
    var labels = [];
    for (var i = lo; i <= hi; i++) labels.push(String(i));
    freqChart(id, nums.map(String), labels, nums.length);
}
function scatterChart(id, pts) {
    new Chart(document.getElementById(id), {
        type: 'scatter',
        data: { datasets: [{ data: pts,
                             backgroundColor: '#4f7ef8bb', pointRadius: 8 }] },
        options: {
            responsive: true, maintainAspectRatio: false,
            plugins: { legend:{ display:false }, tooltip:{ callbacks:{
                label: function(c){ return c.raw.t || String(c.raw.x); }
            }}},
            scales: {
                x: { beginAtZero:true, ticks:{ stepSize:1, precision:0 },
                     title:{ display:true, text:'גיל' } },
                y: { display:false, min:0 }
            }
        }
    });
}
'''

# ── page shell ────────────────────────────────────────────────────────────────

def page(filename, body_js, ts):
    idx   = PAGES.index(filename)
    title = TITLES[filename]
    prev  = PAGES[idx-1] if idx > 0           else None
    nxt   = PAGES[idx+1] if idx < len(PAGES)-1 else None
    pb = '<a href="'+prev+'">&#8594; הקודם</a>' if prev else '<span></span>'
    nb = '<a href="'+nxt+'" class="primary">הבא &#8592;</a>' if nxt else '<span></span>'
    pg = str(idx+1)+' / '+str(len(PAGES))
    return (
        '<!DOCTYPE html>\n<html lang="he" dir="rtl">\n<head>\n'
        '<meta charset="UTF-8">\n'
        '<meta name="viewport" content="width=device-width,initial-scale=1">\n'
        '<title>'+title+' — Grooshi Survey</title>\n'
        '<script src="'+CHARTJS+'"></script>\n'
        '<script src="data.js"></script>\n'
        '<style>'+CSS+'</style>\n'
        '</head>\n<body>\n'
        '<div class="topbar"><h1>Grooshi Survey — '+title+'</h1>'
        '<span class="snap">'+ts+'</span></div>\n'
        '<div class="nav">'+pb+'<span class="pg">'+pg+'</span>'+nb+'</div>\n'
        '<div class="wrap" id="wrap">'
        '<h2 class="ptitle">'+title+'</h2>'
        '<p class="psub" id="psub"></p>'
        '</div>\n'
        '<footer>Snapshot: '+ts+'</footer>\n'
        '<script>\n'
        + SHARED_JS + '\n'
        'var D = SURVEY_DATA;\n'
        'var N = D.length;\n'
        'document.getElementById("psub").textContent = N + " תגובות";\n'
        + body_js + '\n'
        '</script>\n</body>\n</html>'
    )

# ── section body scripts ──────────────────────────────────────────────────────

INDEX_JS = r'''
var potUsers   = D.filter(function(r){ return r._analysis && r._analysis.potential_user   === true; }).length;
var potPayers  = D.filter(function(r){ return r._analysis && r._analysis.potential_payer  === true; }).length;
var uncertain  = D.filter(function(r){ return r._analysis && r._analysis.potential_user   === 'uncertain'; }).length;
var safetyNo   = D.filter(function(r){ return r['2.1_safety'] === 'לא'; }).length;

var sg = document.createElement('div');
sg.className = 'sg';
sg.innerHTML =
    '<div class="st"><div class="n">'+N+'</div><div class="l">תגובות</div></div>'+
    '<div class="st"><div class="n">'+potUsers+'</div><div class="l">משתמשים פוטנציאליים</div></div>'+
    '<div class="st"><div class="n">'+potPayers+'</div><div class="l">משלמים פוטנציאליים</div></div>'+
    '<div class="st"><div class="n">'+safetyNo+'</div><div class="l">דגל בטיחות</div></div>'+
    '<div class="st"><div class="n">'+uncertain+'</div><div class="l">פוטנציאל לא ודאי</div></div>';
document.getElementById('wrap').appendChild(sg);

var withA = D.filter(function(r){ return r._analysis; });
var segVals = withA.map(function(r){
    var c = r._analysis.category || '';
    return c.split('+')[0].split('[')[0].trim();
});
var segSet = {};
segVals.forEach(function(s){ segSet[s] = (segSet[s]||0)+1; });
var segLabels = Object.keys(segSet).sort(function(a,b){ return segSet[b]-segSet[a]; });
addCard('סגמנטים — התפלגות ראשית', withA.length, N, ch('seg','lg'));
freqChart('seg', segVals, segLabels, withA.length);
'''

SECTION1_JS = r'''
var ts = D.map(function(r){ return r['1.1_time_since_sep']; }).filter(Boolean);
addCard('זמן מאז הפרידה', ts.length, N, ch('tsep','md'));
freqChart('tsep', ts, ['עדיין פרודים','עד שנה','1\u20133 שנים','3\u20137 שנים','7+ שנים'], ts.length);

var nk = D.map(function(r){ return r['1.1_num_kids']; }).filter(Boolean).map(Number);
addCard('מספר ילדים', nk.length, N, ch('nk','md'));
histChart('nk', nk, 1, 6);

var aps = [];
D.forEach(function(r, i){
    for (var k = 1; k <= 10; k++){
        var age = r['1.1_kid_age_'+k];
        if (age != null) aps.push({ x: parseInt(age), y: i+1, t: 'משיב '+(i+1)+' — גיל '+age });
    }
});
addCard('גיל ילדים (נקודה לכל ילד)', aps.length+' ילדים', null, ch('ages','dot'));
scatterChart('ages', aps);

var cu = D.map(function(r){ return r['1.1_custody']; }).filter(Boolean);
addCard('סדר משמורת', cu.length, N, ch('cu','md'));
freqChart('cu', cu, ['\u05de\u05e9\u05de\u05d5\u05e8\u05ea \u05de\u05dc\u05d0\u05d4 \u05e9\u05dc\u05d9','\u05de\u05e9\u05de\u05d5\u05e8\u05ea \u05de\u05e9\u05d5\u05ea\u05e4\u05ea','\u05de\u05e9\u05de\u05d5\u05e8\u05ea \u05de\u05dc\u05d0\u05d4 \u05e9\u05dc \u05d4\u05d4\u05d5\u05e8\u05d4 \u05d4\u05d0\u05d7\u05e8'], cu.length);

var di = D.map(function(r){ return r['1.1_distance']; }).filter(Boolean);
addCard('מרחק מגורים', di.length, N, ch('di','sm'));
freqChart('di', di, ['\u05d0\u05d5\u05ea\u05d4 \u05e2\u05d9\u05e8','\u05e2\u05d9\u05e8 \u05d0\u05d7\u05e8\u05ea','\u05d7\u05d5"\u05dc'], di.length);

var ge = D.map(function(r){ return r['1.2_gender']; }).filter(Boolean);
addCard('מגדר', ge.length, N, ch('ge','sm'));
freqChart('ge', ge, ['\u05e0\u05e7\u05d1\u05d4','\u05d6\u05db\u05e8','\u05d0\u05d7\u05e8'], ge.length);

var rd = D.map(function(r){ return r['1.2_religious_divorce']; }).filter(Boolean);
addCard('גט דתי', rd.length, N, ch('rd','md'));
freqChart('rd', rd, ['\u05d2\u05e8\u05d5\u05e9/\u05d4 \u05d3\u05ea\u05d9\u05ea','\u05d1\u05ea\u05d4\u05dc\u05d9\u05da','\u05e2\u05d9\u05d2\u05d5\u05df','\u05dc\u05d0 \u05e8\u05dc\u05d5\u05d5\u05e0\u05d8\u05d9'], rd.length);

var np = D.map(function(r){ return r['1.2_new_partner']; }).filter(Boolean);
addCard('בן/בת זוג חדש/ה', np.length, N, ch('np','md'));
freqChart('np', np, ['\u05dc\u05d0\u05e3 \u05d0\u05d7\u05d3','\u05dc\u05d9 \u05d1\u05dc\u05d1\u05d3','\u05dc\u05e9\u05d5\u05ea\u05e4/\u05ea \u05d4\u05d4\u05d5\u05e8\u05d5\u05ea \u05d1\u05dc\u05d1\u05d3','\u05dc\u05e9\u05e0\u05d9\u05e0\u05d5'], np.length);
'''

SECTION2_JS = r'''
var sf = D.map(function(r){ return r['2.1_safety']; }).filter(Boolean);
addCard('תחושת ביטחון בתקשורת', sf.length, N, ch('sf','sm'));
freqChart('sf', sf, ['\u05db\u05df','\u05d1\u05e8\u05d5\u05d1 \u05d4\u05de\u05e7\u05e8\u05d9\u05dd','\u05dc\u05d0'], sf.length);

var cf = D.map(function(r){ return r['2.2_comm_frequency']; }).filter(Boolean);
addCard('תדירות תקשורת', cf.length, N, ch('cf','md'));
freqChart('cf', cf, ['\u05db\u05dc \u05db\u05de\u05d4 \u05d9\u05de\u05d9\u05dd','\u05db\u05dc \u05db\u05de\u05d4 \u05e9\u05d1\u05d5\u05e2\u05d5\u05ea','\u05db\u05dc \u05db\u05de\u05d4 \u05d7\u05d5\u05d3\u05e9\u05d9\u05dd','\u05db\u05de\u05e2\u05d8 \u05d5\u05d1\u05db\u05dc\u05dc \u05dc\u05d0'], cf.length);

var cqL = ['1 \u2014 \u05e9\u05d9\u05ea\u05d5\u05e4\u05d9\u05ea (\u05db\u05de\u05e2\u05d8 \u05d7\u05d1\u05e8\u05d9\u05dd)',
           '2 \u2014 \u05e2\u05e1\u05e7\u05d9\u05ea (\u05de\u05ea\u05e7\u05e9\u05e8\u05d9\u05dd \u05db\u05e9\u05e6\u05e8\u05d9\u05da)',
           '3 \u2014 \u05de\u05d5\u05e8\u05db\u05d1\u05ea (\u05e0\u05d0\u05dc\u05e6\u05d9\u05dd \u05dc\u05ea\u05e7\u05e9\u05e8)',
           '4 \u2014 \u05de\u05e1\u05d5\u05d1\u05db\u05ea (\u05de\u05d0\u05d3 \u05e8\u05d2\u05e9\u05d9\u05ea)',
           '5 \u2014 \u05de\u05ea\u05e1\u05db\u05dc\u05ea (\u05d4\u05ea\u05e7\u05e9\u05d5\u05e8\u05ea \u05e7\u05e9\u05d4 \u05dc\u05d9)'];
var cq = D.map(function(r){ return r['2.2_comm_quality']; }).filter(Boolean);
var cqM = cq.map(function(v){ return cqL[parseInt(v)-1]; });
addCard('איכות תקשורת (1=שיתופית, 5=מתסכלת)', cq.length, N, ch('cq','lg'));
freqChart('cq', cqM, cqL, cq.length);

var etL = ['1 \u2014 \u05d0\u05d9\u05df','2 \u2014 \u05e7\u05dc','3 \u2014 \u05d1\u05d9\u05e0\u05d5\u05e0\u05d9','4 \u2014 \u05d7\u05d6\u05e7'];
var et = D.map(function(r){ return r['2.2_emotional_tension']; }).filter(Boolean);
var etM = et.map(function(v){ return etL[parseInt(v)-1]; });
addCard('עוצמה רגשית (1=אין, 4=חזק)', et.length, N, ch('et','md'));
freqChart('et', etM, etL, et.length);

var odL = ['1 \u2014 \u05d0\u05d9\u05df','2 \u2014 \u05e7\u05dc','3 \u2014 \u05d1\u05d9\u05e0\u05d5\u05e0\u05d9','4 \u2014 \u05d7\u05d6\u05e7'];
var od = D.map(function(r){ return r['2.2_org_difficulty']; }).filter(Boolean);
var odM = od.map(function(v){ return odL[parseInt(v)-1]; });
addCard('קושי ארגוני (1=אין, 4=חזק)', od.length, N, ch('od','md'));
freqChart('od', odM, odL, od.length);

var le = D.map(function(r){ return r['2.3_legal']; }).filter(Boolean);
addCard('הליכים משפטיים', le.length, N, ch('le','sm'));
freqChart('le', le, ['\u05d9\u05e9 \u05d4\u05dc\u05d9\u05db\u05d9\u05dd \u05e4\u05e2\u05d9\u05dc\u05d9\u05dd','\u05d4\u05d9\u05d5 \u05d1\u05e2\u05d1\u05e8','\u05dc\u05d0'], le.length);

var ltBase = D.filter(function(r){ return r['2.3_legal'] && r['2.3_legal'] !== '\u05dc\u05d0'; });
var lt = ltBase.map(function(r){ return r['2.3_legal_type']; }).filter(Boolean);
addCard('סוג הליך משפטי', lt.length, ltBase.length, ch('lt','md'));
multiFreq('lt', lt, ['\u05de\u05e9\u05de\u05d5\u05e8\u05ea','\u05de\u05d6\u05d5\u05e0\u05d5\u05ea','\u05e8\u05db\u05d5\u05e9','\u05d2\u05d8','\u05d0\u05d7\u05e8'], ltBase.length);
'''

SECTION3_JS = r'''
var ns = D.filter(function(r){ return r['2.1_safety'] !== '\u05dc\u05d0'; });
var nsN = ns.length;
var frL = ['1 \u2014 \u05de\u05e1\u05ea\u05d3\u05e8\u05d9\u05dd',
           '2 \u2014 \u05dc\u05e4\u05e2\u05de\u05d9\u05dd \u05e7\u05e9\u05d4',
           '3 \u2014 \u05e7\u05e9\u05d4 \u05dc\u05e2\u05d9\u05ea\u05d9\u05dd \u05e7\u05e8\u05d5\u05d1\u05d5\u05ea',
           '4 \u2014 \u05de\u05d0\u05d5\u05d3 \u05e7\u05e9\u05d4 \u05dc\u05e0\u05d5'];

var ar = ns.map(function(r){ return r['3.1_areas']; }).filter(Boolean);
addCard('תחומי חיכוך', ar.length, nsN, ch('ar','md'));
multiFreq('ar', ar, ['\u05e9\u05d2\u05e8\u05d4 \u05d5\u05de\u05d8\u05dc\u05d5\u05ea','\u05e9\u05d9\u05e0\u05d5\u05d9\u05d9 \u05dc\u05d5"\u05d6','\u05e7\u05d1\u05dc\u05ea \u05d4\u05d7\u05dc\u05d8\u05d5\u05ea','\u05e0\u05d9\u05d4\u05d5\u05dc \u05db\u05e1\u05e4\u05d9\u05dd \u05d5\u05d4\u05d5\u05e6\u05d0\u05d5\u05ea','\u05d0\u05d7\u05e8'], nsN);

var ch3 = ns.map(function(r){ return r['3_channels']; }).filter(Boolean);
addCard('ערוצי תקשורת', ch3.length, nsN, ch('ch3','lg'));
multiFreq('ch3', ch3, ['\u05d5\u05d5\u05d0\u05d8\u05e1\u05d0\u05e4','\u05e9\u05d9\u05d7\u05ea \u05d8\u05dc\u05e4\u05d5\u05df','\u05d0\u05d9\u05de\u05d9\u05d9\u05dc','\u05d0\u05e7\u05e1\u05dc','\u05e9\u05d9\u05d7\u05d5\u05ea \u05e4\u05e0\u05d9\u05dd \u05d0\u05dc \u05e4\u05e0\u05d9\u05dd','\u05d0\u05e4\u05dc\u05d9\u05e7\u05e6\u05d9\u05d4 \u05d9\u05d9\u05e2\u05d5\u05d3\u05d9\u05ea','\u05d0\u05d7\u05e8'], nsN);

var ff = ns.map(function(r){ return r['3_friction_frequency']; }).filter(Boolean);
addCard('תדירות חיכוך', ff.length, nsN, ch('ff','md'));
freqChart('ff', ff, ['\u05db\u05dc \u05db\u05de\u05d4 \u05d9\u05de\u05d9\u05dd','\u05db\u05dc \u05db\u05de\u05d4 \u05e9\u05d1\u05d5\u05e2\u05d5\u05ea','\u05db\u05dc \u05db\u05de\u05d4 \u05d7\u05d5\u05d3\u05e9\u05d9\u05dd','\u05d1\u05db\u05dc\u05dc \u05dc\u05d0'], ff.length);

var areas = [
  { key: '\u05e9\u05d2\u05e8\u05d4 \u05d5\u05de\u05d8\u05dc\u05d5\u05ea', ff: '3_routine_friction', cf: '3_routine_cause',
    fid: 'ruf', cid: 'ruc', ftitle: '\u05d7\u05d9\u05db\u05d5\u05da \u2014 \u05e9\u05d2\u05e8\u05d4 \u05d5\u05de\u05d8\u05dc\u05d5\u05ea',
    ctitle: '\u05d2\u05d5\u05e8\u05de\u05d9 \u05d7\u05d9\u05db\u05d5\u05da \u2014 \u05e9\u05d2\u05e8\u05d4',
    copts: ['\u05d4\u05e2\u05d1\u05e8\u05ea \u05de\u05d9\u05d3\u05e2 \u05d7\u05dc\u05e7\u05d9\u05ea \u05d0\u05d5 \u05d7\u05e1\u05e8\u05d4','\u05d4\u05e2\u05d5\u05de\u05e1 \u05d1\u05e9\u05d2\u05e8\u05d4 \u05d0\u05d9\u05e0\u05d5 \u05e9\u05d9\u05d5\u05d5\u05d9\u05d5\u05e0\u05d9','\u05e9\u05db\u05d7\u05d4 \u05d0\u05d5 \u05d0\u05d9-\u05e2\u05de\u05d9\u05d3\u05d4 \u05d1\u05de\u05d4 \u05e9\u05e1\u05d5\u05db\u05dd','\u05ea\u05d2\u05d5\u05d1\u05d4 \u05d0\u05d9\u05d8\u05d9\u05ea \u05d0\u05d5 \u05d7\u05d5\u05e1\u05e8 \u05d6\u05de\u05d9\u05e0\u05d5\u05ea \u05dc\u05ea\u05d9\u05d0\u05d5\u05dd','\u05e9\u05d9\u05e0\u05d5\u05d9\u05d9\u05dd \u05d0\u05d5 \u05d1\u05d9\u05d8\u05d5\u05dc\u05d9\u05dd \u05d1\u05e8\u05d2\u05e2 \u05d4\u05d0\u05d7\u05e8\u05d5\u05df','\u05d0\u05d7\u05e8'] },
  { key: '\u05e9\u05d9\u05e0\u05d5\u05d9\u05d9 \u05dc\u05d5"\u05d6', ff: '3_schedule_friction', cf: '3_schedule_cause',
    fid: 'scf', cid: 'scc', ftitle: '\u05d7\u05d9\u05db\u05d5\u05da \u2014 \u05e9\u05d9\u05e0\u05d5\u05d9\u05d9 \u05dc\u05d5"\u05d6',
    ctitle: '\u05d2\u05d5\u05e8\u05de\u05d9 \u05d7\u05d9\u05db\u05d5\u05da \u2014 \u05dc\u05d5"\u05d6',
    copts: ['\u05d1\u05e7\u05e9\u05d5\u05ea \u05dc\u05e9\u05d9\u05e0\u05d5\u05d9\u05d9\u05dd \u05d1\u05e8\u05d2\u05e2 \u05d4\u05d0\u05d7\u05e8\u05d5\u05df','\u05e7\u05d5\u05e9\u05d9 \u05d1\u05ea\u05d9\u05d0\u05d5\u05dd \u05dc\u05d5\u05d7\u05d5\u05ea \u05d6\u05de\u05e0\u05d9\u05dd','\u05d0\u05d9-\u05e2\u05de\u05d9\u05d3\u05d4 \u05d1\u05e1\u05d9\u05db\u05d5\u05de\u05d9\u05dd','\u05d0\u05d7\u05e8'] },
  { key: '\u05e7\u05d1\u05dc\u05ea \u05d4\u05d7\u05dc\u05d8\u05d5\u05ea', ff: '3_decisions_friction', cf: '3_decisions_cause',
    fid: 'def', cid: 'dec', ftitle: '\u05d7\u05d9\u05db\u05d5\u05da \u2014 \u05e7\u05d1\u05dc\u05ea \u05d4\u05d7\u05dc\u05d8\u05d5\u05ea',
    ctitle: '\u05d2\u05d5\u05e8\u05de\u05d9 \u05d7\u05d9\u05db\u05d5\u05da \u2014 \u05d4\u05d7\u05dc\u05d8\u05d5\u05ea',
    copts: ['\u05db\u05dc \u05e6\u05d3 \u05de\u05ea\u05e2\u05e7\u05e9 \u05e2\u05dc \u05d4\u05d3\u05e8\u05da \u05e9\u05dc\u05d5','\u05e6\u05d3 \u05d0\u05d7\u05d3 \u05de\u05d7\u05dc\u05d9\u05d8 \u05d1\u05dc\u05d9 \u05dc\u05d4\u05ea\u05d9\u05d9\u05e2\u05e5','\u05db\u05dc \u05d4\u05ea\u05d9\u05d9\u05e2\u05e6\u05d5\u05ea \u05d4\u05d5\u05e4\u05db\u05ea \u05dc\u05d5\u05d5\u05d9\u05db\u05d5\u05d7','\u05e2\u05d9\u05db\u05d5\u05d1 \u05d0\u05d5 \u05d0\u05d9-\u05de\u05e2\u05e0\u05d4 \u05db\u05e9\u05e0\u05d3\u05e8\u05e9\u05ea \u05ea\u05d2\u05d5\u05d1\u05d4','\u05de\u05d9\u05d3\u05e2 \u05e8\u05dc\u05d5\u05d5\u05e0\u05d8\u05d9 \u05dc\u05d0 \u05de\u05ea\u05d5\u05e7\u05e9\u05e8 \u05d1\u05d9\u05df \u05d4\u05e6\u05d3\u05d3\u05d9\u05dd','\u05d0\u05d7\u05e8'] },
  { key: '\u05e0\u05d9\u05d4\u05d5\u05dc \u05db\u05e1\u05e4\u05d9\u05dd \u05d5\u05d4\u05d5\u05e6\u05d0\u05d5\u05ea', ff: '3_finances_friction', cf: '3_finances_cause',
    fid: 'fif', cid: 'fic', ftitle: '\u05d7\u05d9\u05db\u05d5\u05da \u2014 \u05db\u05e1\u05e4\u05d9\u05dd',
    ctitle: '\u05d2\u05d5\u05e8\u05de\u05d9 \u05d7\u05d9\u05db\u05d5\u05da \u2014 \u05db\u05e1\u05e4\u05d9\u05dd',
    copts: ['\u05d7\u05d5\u05e1\u05e8 \u05e9\u05e7\u05d9\u05e4\u05d5\u05ea \u05d5\u05ea\u05d9\u05e2\u05d5\u05d3 \u05e9\u05dc \u05d4\u05d5\u05e6\u05d0\u05d5\u05ea','\u05de\u05d7\u05dc\u05d5\u05e7\u05d5\u05ea \u05e2\u05dc \u05d7\u05dc\u05d5\u05e7\u05ea \u05d4\u05e0\u05d8\u05dc \u05d4\u05db\u05e1\u05e4\u05d9 \u05d1\u05d9\u05df \u05d4\u05d4\u05d5\u05e8\u05d9\u05dd','\u05de\u05d7\u05dc\u05d5\u05e7\u05d5\u05ea \u05e2\u05dc \u05de\u05d4 \u05e0\u05d7\u05e9\u05d1 \u05d4\u05d5\u05e6\u05d0\u05d4 \u05de\u05e9\u05d5\u05ea\u05e4\u05ea','\u05e9\u05d9\u05de\u05d5\u05e9 \u05d1\u05db\u05e1\u05e3 \u05db\u05db\u05dc\u05d9 \u05dc\u05d7\u05e5 \u05d0\u05d5 \u05e2\u05e0\u05d9\u05e9\u05d4','\u05d0\u05d7\u05e8'] }
];

areas.forEach(function(a){
    var base = ns.filter(function(r){
        var v = r['3.1_areas'] || '';
        return v.indexOf(a.key) !== -1;
    });
    if (base.length === 0) return;
    var fv = base.map(function(r){ return r[a.ff]; }).filter(Boolean);
    var fvM = fv.map(function(v){ return frL[parseInt(v)-1]; });
    addCard(a.ftitle, fv.length, base.length, ch(a.fid,'md'));
    freqChart(a.fid, fvM, frL, fv.length);
    var cv = base.map(function(r){ return r[a.cf]; }).filter(Boolean);
    addCard(a.ctitle, cv.length, base.length, ch(a.cid,'lg'));
    multiFreq(a.cid, cv, a.copts, cv.length);
});

var mr = ns.map(function(r){ return r['3_mediator_role']; }).filter(Boolean);
addCard('תפקיד המגשר הרצוי', mr.length, nsN, ch('mr','xl'));
multiFreq('mr', mr, [
    '\u05dc\u05e9\u05de\u05d5\u05e8 \u05d4\u05d9\u05e1\u05d8\u05d5\u05e8\u05d9\u05d4 \u05e9\u05e0\u05d9\u05ea\u05df \u05dc\u05d7\u05d6\u05d5\u05e8 \u05d0\u05dc\u05d9\u05d4',
    '\u05dc\u05d4\u05e2\u05d1\u05d9\u05e8 \u05d1\u05d9\u05e0\u05d9\u05e0\u05d5 \u05de\u05d9\u05d3\u05e2 \u05dc\u05d2\u05d1\u05d9 \u05d4\u05d9\u05dc\u05d3',
    '\u05dc\u05ea\u05d6\u05db\u05e8 \u05d5\u05dc\u05e2\u05e7\u05d5\u05d1 \u05d0\u05d7\u05e8 \u05d4\u05ea\u05d7\u05d9\u05d9\u05d1\u05d5\u05d9\u05d5\u05ea',
    '\u05dc\u05e0\u05e1\u05d7 \u05d4\u05d5\u05d3\u05e2\u05d5\u05ea \u05e9\u05de\u05d5\u05e0\u05e2\u05d5\u05ea \u05d4\u05e1\u05dc\u05de\u05d4 \u05e8\u05d2\u05e9\u05d9\u05ea',
    '\u05dc\u05e0\u05d4\u05dc \u05de\u05e2\u05e7\u05d1 \u05e9\u05e7\u05d5\u05e3 \u05e9\u05dc \u05db\u05e1\u05e4\u05d9\u05dd',
    '\u05dc\u05d4\u05e6\u05d9\u05e2 \u05e4\u05ea\u05e8\u05d5\u05df \u05e0\u05d9\u05d8\u05e8\u05dc\u05d9 \u05dc\u05de\u05d7\u05dc\u05d5\u05e7\u05d5\u05ea',
    '\u05dc\u05ea\u05d0\u05dd \u05e2\u05dd \u05d2\u05d5\u05e8\u05de\u05d9\u05dd \u05d7\u05d9\u05e6\u05d5\u05e0\u05d9\u05d9\u05dd \u05d1\u05de\u05e7\u05d5\u05de\u05e0\u05d5',
    '\u05d0\u05d7\u05e8'], nsN);
'''

SECTION4_JS = r'''
var ba = D.map(function(r){ return r['4_barriers']; }).filter(Boolean);
addCard('חסמים לאימוץ', ba.length, N, ch('ba','lg'));
multiFreq('ba', ba, [
    '\u05de\u05d5\u05e8\u05db\u05d1\u05d5\u05ea \u05d8\u05db\u05e0\u05d9\u05ea',
    '\u05d7\u05e9\u05e9 \u05e9\u05d4\u05d5\u05e8\u05d4 \u05d4\u05d0\u05d7\u05e8 \u05dc\u05d0 \u05d9\u05e9\u05ea\u05e3 \u05e4\u05e2\u05d5\u05dc\u05d4',
    '\u05d7\u05e9\u05d9\u05e4\u05ea \u05de\u05d9\u05d3\u05e2 \u05e4\u05e8\u05d8\u05d9',
    '\u05e2\u05dc\u05d5\u05ea',
    '\u05d7\u05d5\u05e1\u05e8 \u05d0\u05de\u05d5\u05df \u05d1\u05d2\u05d5\u05e8\u05dd \u05d7\u05d9\u05e6\u05d5\u05e0\u05d9',
    '\u05d0\u05d7\u05e8'], N);

var wt = D.map(function(r){ return r['4_wtp']; }).filter(Boolean);
addCard('נכונות לתשלום', wt.length, N, ch('wt','sm'));
freqChart('wt', wt, ['\u05db\u05df','\u05dc\u05d0'], wt.length);

var wtBase = D.filter(function(r){ return r['4_wtp'] === '\u05db\u05df'; });
var wr = wtBase.map(function(r){ return r['4_wtp_range']; }).filter(Boolean);
addCard('טווח תשלום', wr.length, wtBase.length, ch('wr','md'));
freqChart('wr', wr, [
    '\u05e2\u05d3 \u20aa20/\u05d7\u05d5\u05d3\u05e9',
    '\u20aa20\u201350/\u05d7\u05d5\u05d3\u05e9',
    '\u20aa50\u2013100/\u05d7\u05d5\u05d3\u05e9',
    '\u05de\u05e2\u05dc \u20aa100/\u05d7\u05d5\u05d3\u05e9',
    '\u05ea\u05e9\u05dc\u05d5\u05dd \u05d7\u05d3-\u05e4\u05e2\u05de\u05d9'], wr.length);
'''

SECTION5_JS = r'''
var of2 = D.map(function(r){ return r['5_other_filled']; }).filter(Boolean);
addCard('מילוי סקר נוסף', of2.length, N, ch('of2','sm'));
freqChart('of2', of2, ['\u05db\u05df','\u05dc\u05d0'], of2.length);

var co = D.map(function(r){ return r['5_contact_ok']; }).filter(Boolean);
addCard('הסכמה לפנייה', co.length, N, ch('co','sm'));
freqChart('co', co, ['\u05db\u05df','\u05dc\u05d0'], co.length);
'''

META_JS = r'''
function dynChart(id, vals, title) {
    if (vals.length === 0) return;
    var set = {};
    vals.forEach(function(v){ set[v] = (set[v]||0)+1; });
    var labels = Object.keys(set).sort(function(a,b){ return set[b]-set[a]; });
    var sz = labels.length <= 3 ? 'sm' : labels.length <= 6 ? 'md' : 'lg';
    addCard(title, vals.length, N, ch(id, sz));
    freqChart(id, vals, labels, vals.length);
}
dynChart('camp', D.map(function(r){ return r['_utm_campaign']; }).filter(Boolean), 'utm_campaign');
dynChart('ref',  D.map(function(r){ return r['_referrer_source']; }).filter(Boolean), 'referrer_source');
dynChart('usrc', D.map(function(r){ return r['_utm_source']; }).filter(Boolean), 'utm_source');
dynChart('umed', D.map(function(r){ return r['_utm_medium']; }).filter(Boolean), 'utm_medium');
'''

ANALYSIS_JS = r'''
var wa = D.filter(function(r){ return r._analysis; });
var sv = wa.map(function(r){
    var c = r._analysis.category || '';
    return c.split('+')[0].split('[')[0].trim();
});
var ss = {};
sv.forEach(function(s){ ss[s]=(ss[s]||0)+1; });
var sl = Object.keys(ss).sort(function(a,b){ return ss[b]-ss[a]; });
addCard('\u05e1\u05d2\u05de\u05e0\u05d8 \u05e8\u05d0\u05e9\u05d9', wa.length, N, ch('seg','lg'));
freqChart('seg', sv, sl, wa.length);

var puV = wa.map(function(r){ return String(r._analysis.potential_user); });
addCard('\u05de\u05e9\u05ea\u05de\u05e9 \u05e4\u05d5\u05d8\u05e0\u05e6\u05d9\u05d0\u05dc\u05d9', wa.length, N, ch('pu','sm'));
freqChart('pu', puV, ['true','uncertain','false'], wa.length);

var ppV = wa.map(function(r){ return String(r._analysis.potential_payer); });
addCard('\u05de\u05e9\u05dc\u05dd \u05e4\u05d5\u05d8\u05e0\u05e6\u05d9\u05d0\u05dc\u05d9', wa.length, N, ch('pp','sm'));
freqChart('pp', ppV, ['true','false'], wa.length);
'''

# ── main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--data-only', action='store_true',
                        help='Regenerate data.js only; leave all HTML files untouched.')
    args = parser.parse_args()

    ts = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    responses = load_responses()
    write_data_js(responses, ts)
    print('data.js written ({} responses)'.format(len(responses)))

    if args.data_only:
        print('\nDone (data only). HTML files were not modified.')
        return

    pages = {
        'index.html':    INDEX_JS,
        'section1.html': SECTION1_JS,
        'section2.html': SECTION2_JS,
        'section3.html': SECTION3_JS,
        'section4.html': SECTION4_JS,
        'section5.html': SECTION5_JS,
        'meta.html':     META_JS,
        'analysis.html': ANALYSIS_JS,
    }
    for filename, body_js in pages.items():
        html = page(filename, body_js, ts)
        (OUT_DIR / filename).write_text(html, encoding='utf-8')
        print('written: analysis/' + filename)

    print('\nDone. Open analysis/index.html in your browser.')

if __name__ == '__main__':
    main()
